CORS done
UNIZAR-30246-WebEngineering/lab2-web-server pull request #29
Opened 2022-10-22 20:20 UTC by hec7orci7o

2022-10-23 21:30 UTC, fjlopez requested changes
`README.md` describes a valid approach to CORS but it is not used in the Controller. Please, update it.

2022-10-23 21:30 UTC, fjlopez commented on README.md
> +- ~**CORS what?**: Enables [CORS](https://developer.mozilla.org/es/docs/Web/HTTP/CORS) support and provides a JUnit-based test to prove it.~ solved by [hec7orci7o](https://github.com/Hec7or-Uni/lab1-
Point to your `work` branch in `lab 2`.

2022-10-25 11:24 UTC, hec7orci7o reviewed
work branch linked

2022-10-31 14:38 UTC, merged

2022-10-31 14:38 UTC, fjlopez commented
Merged!